version: '3'
services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
